### ISSUE TITLE
Texture's error when you load a resourcepack and relog.

### ISSUE THREAD

**Issue by HUNAttila32** [TheBossMagnus/Thunder#12]
Everything said above.

**Comment by TheBossMagnus** [comment]
Thank you for reporting the bug!
Can you send me a screenshot of the issue?
Also the thunder version, the Minecraft version and the mod loader used might be helpful...

**Comment by HUNAttila32** [comment]
I used Thunder 1.2.12 when the bug happens. I'm gonna update and assume it was a bug with 1 of the mods. 1.20.1, Prism Launcher.

**Comment by TheBossMagnus** [comment]
(Most likely) found the problem!
I experienced a crash when loading that resourcepack...
Try removing Modernfix from the instance.
I'll report the bug to modernfix's dev

**Comment by TheBossMagnus** [comment]
The Next release should fix this bug

**Comment by HUNAttila32** [comment]
alr

**Comment by TheBossMagnus** [comment]
fixed in the latest version (1.2.15)
