### ISSUE TITLE
Threadtweak is outdated in 1.20.5

### ISSUE THREAD

**Issue by renovat3** [TheBossMagnus/Thunder#18]
sry im not a english native speaker
When I launch minecraft, this appears:
Mod 'ThreadTweak' (threadtweak) 1.20.4-0.1.2 requires version 1.20.4 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.5!

**Comment by TheBossMagnus** [comment]
Have you somehow delated the file (fabric_loader_dependencies.json)[https://github.com/TheBossMagnus/Thunder/blob/main/src/1.20.5/fabric/config/fabric_loader_dependencies.json] ? If that's the case readd it and everything should work fine.

Threadtweak isn't yet officially available for 1.20.5, but with this hacky workaround i was able to make it work just fine.

**Comment by TheBossMagnus** [comment]
@renovat3 does this still happens on https://modrinth.com/modpack/thunder/version/1.2.1+1.20.5 or https://modrinth.com/modpack/thunder/version/1.0.1+1.20.6 ? ty

**Comment by TheBossMagnus** [comment]
Closing due to no answer
